package nl.eduid.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFA4C9FF)
val md_theme_dark_onPrimary = Color(0xFF00315D)
val md_theme_dark_primaryContainer = Color(0xFF004883)
val md_theme_dark_onPrimaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_secondary = Color(0xFFA4C9FF)
val md_theme_dark_onSecondary = Color(0xFF00315D)
val md_theme_dark_secondaryContainer = Color(0xFF004883)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_tertiary = Color(0xFF4FD8EB)
val md_theme_dark_onTertiary = Color(0xFF00363D)
val md_theme_dark_tertiaryContainer = Color(0xFF004F58)
val md_theme_dark_onTertiaryContainer = Color(0xFF97F0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C6CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF0060AC)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA4C9FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)

val MainSurfGreen = Color(0xFF008939)
val TextBlack = Color(0xFF050E1D)
val SplashScreenBackgroundColor = Color(0xFF0062B0)
val ButtonTextGrey = Color(0xFF5E6873)
val TextGrey = Color(0xFF5B5B5B)
val AlertWarningBackground = Color(0xFFFEF8D3)
val BlueButton = Color(0xFF004C97)
val TextGrayScale = Color(0xFF5E6873)
val BlueText = Color(0xFF173552)
val ButtonRed = Color(0xFFDA362D)
val InfoTabDarkFill = Color(0xFFF4F6F8)
val ButtonBorderGrey = Color(0xFF5E6873)
val AlertRedBackground = Color(0xFFFFCDCA)
val SmallActionGray = Color(0xFFB2B6BE)

val SupportBlue400 = Color(0xFF0077C8)
val AlertInfoBackground = Color(0xFFB3E5FF)