# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build app and upload to Firebase App Distribution"
  lane :bundle_for_distribution  do
      gradle(task: "clean assembleAcceptance",
        properties: {
          "android.injected.signing.store.file" => 'app_distribution_keystore.jks',
          "android.injected.signing.store.password" => 'eduideduid',
          "android.injected.signing.key.alias" => 'eduid',
          "android.injected.signing.key.password" => 'eduideduid',
          "commit" => ENV["GIT_COMMIT"],
        }

      )
      firebase_app_distribution(
          app: ENV["FIREBASE_APP_ID_ANDROID"],
          firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
          groups: "internal-testers-eduid",
          release_notes: `printf 'Build #%s [%s]' $BUILD_NUMBER $GIT_COMMIT` + "\n\nChanges:\n" + `git log --pretty=format:"* %b [%h]" --merges --first-parent develop --max-count 50`,
      )
  end
end